// Stub for `astro:content` used only when running tests under Vitest.
// Vite (and therefore Vitest) cannot resolve the real `astro:content`
// virtual module because it is generated by Astro's build pipeline.
// vitest.config.ts aliases `astro:content` to this file so imports resolve;
// individual tests use `vi.mock('astro:content', ...)` to provide their
// own implementations of these exports.

export async function getCollection(_name: string, _filter?: (entry: unknown) => boolean) {
  return [] as unknown[];
}

export function defineCollection<T>(config: T): T {
  return config;
}

// Minimal `z` shim — only the helpers our schema touches need to exist as
// callables. Tests never validate against this.
const passthrough = () => {
  const obj: Record<string, unknown> = {
    optional: () => passthrough(),
    default: () => passthrough(),
    parse: (v: unknown) => v,
  };
  return obj;
};

export const z = {
  object: passthrough,
  string: passthrough,
  array: passthrough,
  boolean: passthrough,
  coerce: { date: passthrough },
};
